brain_two/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoDetailView,
    TodoListView,
    TodoCreateView,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="list_todos"),
    path("<int:pk>/", TodoDetailView.as_view(), name="show_todolist"),
    path("create/", TodoCreateView.as_view(), name="create_todolist"),
]

todos/models.py
from django.db import models

# Create your models here.

class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True,blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        task = str(self.task)
        return task

todos/views.py
#from django.shortcuts import render

from django.views.generic import ListView, DetailView, CreateView

from todos.models import TodoList

# Create your views here.
class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"

class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"

class TodoCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]
    success_url = "/todos/"

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do Lists</title>
</head>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>

todos/templates/todos/create.html
{% block content %}
<main>
    <div>
        <h1>"Create a new list"</h1>
        <form method="POST">
            {% csrf_token %}
            Name: <input type="text" name="name">
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}

todos/templates/todos/detail.html
{% block content %}
<main>
    <div>
        <h1>{{ todolist.name }}</h1>
        <h2>Tasks</h2>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Due Date</th>
                </tr>
            </thead>
            <tbody>
                {% for item in todolist.items.all %}
                <tr>
                    <td>{{ item.task }}</td>
                    <td>{{ item.due_date|date:"M d, Y" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock content %}

todos/templates/todos/list.html
{% block content %}
<main>
    <div>
        <h1>My Lists</h1>
        <div>
            <p>
                <a href="{% url 'create_todolist' %}">Create a new list</a>
            </p>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of Items</th>
                </tr>
            </thead>
            <tbody>
                {% for list in todolist_list %}
                <tr>
                    <td>
                        <a href="{% url 'show_todolist' list.id %}">{{ list.name }}</a>
                    </td>
                    <td>{{ list.items.all|length }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock content %}